services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.config/gcloud/application_default_credentials.json:/app/adc.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/adc.json
      GOOGLE_CLOUD_PROJECT: cs1660-final-group1
