on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # checkout code
      - uses: actions/checkout@v4

      # authenticate with GCP with workload identity provider
      - uses: 'google-github-actions/auth@v2'
        id: auth
        name: Authenticate to GCP
        with:
          project_id: 'cs1660-final-group1' # update with your project ID
          service_account: 'cicd-service-account@cs1660-final-group1.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/1037276530414/locations/global/workloadIdentityPools/github/providers/my-repo' # update with your Workload Identity Pool
          token_format: 'access_token'

      # login Docker to Artifact registry
      - name: Docker login to Artifact Registry
        run: |
          echo "${{ steps.auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev

      # configure/login with docker
      #- name: gcloud Configure Docker
       # run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # setup docker buildx
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      # build and push the image
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/cs1660-final-group1/app-repo/notes-app:v1
          outputs: type=image,push=true
          
